import docx
from docx.shared import Pt, RGBColor, Inches
import os

def create_doc():
    doc = docx.Document()
    
    # Title
    p = doc.add_paragraph()
    runner = p.add_run('Numerical Computing II\nAssignment V — Lagrange Interpolation on Large Datasets\nDate: Aug 22, 2026')
    runner.bold = True
    runner.font.size = Pt(14)
    
    # Intro
    doc.add_paragraph("For this assignment, I updated the Python program to handle large datasets using a Barycentric Lagrange Interpolation approach. Specifically, I processed a dataset of 150 points (student_academic_stress_interpolation_150.csv).")
    doc.add_paragraph("Interpolating large datasets at once with a single high-degree polynomial traditionally results in massive numerical overflow. By using the Barycentric algorithm, we achieve numerical stability and can compute the polynomial safely.")
    
    doc.add_heading('1. Full Dataset (Scatter Plot)', level=1)
    doc.add_paragraph("First, here is a scatter plot showing all 150 data points before any interpolation is applied:")
    
    scatter_path = "outputs/scale_test_scatter.png"
    if os.path.exists(scatter_path):
        doc.add_picture(scatter_path, width=Inches(6.0))
    else:
        doc.add_paragraph(f"[Graph should be here but the image {scatter_path} was not found.]")

    doc.add_heading('2. Runge\'s Phenomenon Progression', level=1)
    doc.add_paragraph("Below, we progressively fit a single polynomial across increasing subsets of the evenly spaced points. This illustrates how the geometric nature of fitting a high-degree polynomial causes wild boundary oscillations known as Runge's Phenomenon, even though the Barycentric method prevents numerical overflow.")
    
    sizes = [5, 20, 50, 100, 150]
    
    for n in sizes:
        doc.add_heading(f'Interpolation with N = {n} Points', level=2)
        doc.add_paragraph(f"This graph shows the interpolating polynomial generated by fitting a degree-{n-1} curve across an evenly spaced subset of {n} points, drawn over the original dataset.")
        
        plot_path = f"outputs/scale_test_N{n}.png"
        if os.path.exists(plot_path):
            doc.add_picture(plot_path, width=Inches(6.0))
        else:
            doc.add_paragraph(f"[Graph should be here but the image {plot_path} was not found.]")
            
        if n == 150:
            doc.add_paragraph("\nAs seen in the final graph (N=150), the boundary fluctuations have become massively chaotic. This visually confirms Runge's Phenomenon.")

    # Save
    doc.save('Assignment5_Barycentric_Lagrange_Interpolation.docx')
    print("Document created successfully as Assignment5_Barycentric_Lagrange_Interpolation.docx")

if __name__ == "__main__":
    create_doc()
